# Generated by Django 3.2.5 on 2021-07-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products_app', '0004_alter_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='images/products'),
        ),
    ]
